jobs:
  include:
    - language: go
      dist: focal
      # Whitelist master so PRs only run one set of tests.
      if: branch = master
      go:
        - '1.14.4'
      addons:
        postgresql: "12"
        apt:
          packages:
            - postgresql-12
            - postgresql-client-12
      env:
        - WKSPH_ARGS_STORAGE_POSTGRES_DBNAME="wikisophia_test"
        - WKSPH_ARGS_STORAGE_POSTGRES_USER="postgres"
      before_script:
        - go get -u golang.org/x/lint/golint
        - psql -c 'create database wikisophia_test;' -U postgres
        - psql -c 'create user app_wikisophia;' -U postgres
      script:
        - ./scripts/test-server.sh
    - language: node_js
      node_js:
        - node
      dist: bionic
      if: branch = master
      install: cd client-js && npm install && cd ..
      script:
        - ./scripts/test-client-js.sh
    - language: node_js
      node_js:
        - node
      dist: bionic
      if: branch = master AND tag =~ /^client-js-\d+\.\d+\.\d+$/
      install: cd client-js && npm ci && cd ..
      deploy:
        - provider: script
          skip_cleanup: true
          script: bash scripts/publish-client-js.sh
          on:
            tags: true
            branch: master