jobs:
  include:
    - language: go
      dist: focal
      # Whitelist master so PRs only run one set of tests.
      if: branch = master
      go:
        - '1.14.6'
      addons:
        postgresql: "12"
      env:
        - WKSPH_ARGUMENTS_STORE_POSTGRES_DBNAME="wikisophia_arguments_test"
        - WKSPH_ARGUMENTS_STORE_POSTGRES_USER="app_wikisophia_arguments_test"
        - WKSPH_ARGUMENTS_STORE_POSTGRES_PASSWORD="app_wikisophia_arguments_test_password"
      before_script:
        - psql -U postgres -v accountsUser="dev_wikisophia_accounts" -v accountsPass="'dev_wikisophia_accounts_password'" -f ./server/accounts/postgres/scripts/bootstrap.sql
        - psql -U postgres -v argumentsUser="dev_wikisophia_arguments" -v argumentsPass="'dev_wikisophia_arguments_password'" -f ./server/arguments/postgres/scripts/bootstrap.sql
        - psql -U postgres -d wikisophia_accounts_test -v accountsUser="app_wikisophia_accounts_test" -f ./server/accounts/postgres/scripts/create.sql
        - psql -U postgres -d wikisophia_accounts_test -v accountsUser="app_wikisophia_accounts_test" -f ./server/accounts/postgres/scripts/grants-for-tests.sql
        - psql -U postgres -d wikisophia_arguments_test -v argumentsUser="app_wikisophia_arguments_test" -f ./server/arguments/postgres/scripts/create.sql
        - psql -U postgres -d wikisophia_arguments_test -v argumentsUser="app_wikisophia_arguments_test" -f ./server/arguments/postgres/scripts/grants-for-tests.sql
      script:
        - ./scripts/test-server.sh
    - language: node_js
      node_js:
        - node
      dist: focal
      if: branch = master
      install: cd client-js && npm install && cd ..
      script:
        - ./scripts/test-client-js.sh
    - language: node_js
      node_js:
        - node
      dist: focal
      if: branch = master AND tag =~ /^client-js-\d+\.\d+\.\d+$/
      install: cd client-js && npm ci && cd ..
      deploy:
        - provider: script
          skip_cleanup: true
          script: bash scripts/publish-client-js.sh
          on:
            tags: true
            branch: master
