language: go
go:
  - '1.10.7'
  - '1.11.4'
services:
  - postgresql
env:
  global:
    - DEP_VERSION="0.5.0"
    - WKSPH_ARGS_STORAGE_POSTGRES_DBNAME="wikisophia_test"
    - WKSPH_ARGS_STORAGE_POSTGRES_USER="postgres"
before_script:
  - psql -c 'create database wikisophia_test;' -U postgres
  - psql -c 'create user app_wikisophia;' -U postgres
install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
script:
  - go test ./...
  - go test ./arguments/postgres -database
  - golint $(go list ./... | grep -v /vendor/)
  - gofmt -w -s .
