jobs:
  include:
    - language: go
      dist: focal
      # Whitelist master so PRs only run one set of tests.
      if: branch = master
      go:
        - '1.14.6'
      addons:
        postgresql: "12"
      env:
        - WKSPH_ARGS_STORAGE_POSTGRES_DBNAME="wikisophia_test"
        - WKSPH_ARGS_STORAGE_POSTGRES_USER="app_wikisophia_test"
        - WKSPH_ARGS_STORAGE_POSTGRES_PASSWORD="app_wikisophia_test_password"
      before_script:
        - psql -U postgres -f ./server/postgres/scripts/bootstrap.sql
      script:
        - ./scripts/test-server.sh
    - language: node_js
      node_js:
        - node
      dist: focal
      if: branch = master
      install: cd client-js && npm install && cd ..
      script:
        - ./scripts/test-client-js.sh
    - language: node_js
      node_js:
        - node
      dist: focal
      if: branch = master AND tag =~ /^client-js-\d+\.\d+\.\d+$/
      install: cd client-js && npm ci && cd ..
      deploy:
        - provider: script
          skip_cleanup: true
          script: bash scripts/publish-client-js.sh
          on:
            tags: true
            branch: master
