language: go
branches:
  only: 
    - master
go:
  - '1.11.4'
services:
  - postgresql
env:
  global:
    - DEP_VERSION="0.5.0"
    - WKSPH_ARGS_STORAGE_POSTGRES_DBNAME="wikisophia_test"
    - WKSPH_ARGS_STORAGE_POSTGRES_USER="postgres"
before_script:
  - go get -u github.com/golang/lint/golint
  - psql -c 'create database wikisophia_test;' -U postgres
  - psql -c 'create user app_wikisophia;' -U postgres
install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - cd server && dep ensure
script:
  - ./test.sh
