[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "~1.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.3.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "^0.8.1"

[[constraint]]
  name = "github.com/smotes/purse"
  version = "^1.0.1"

[[constraint]]
  name = "github.com/rs/cors"
  version = "^1.3.0"

[[constraint]]
  name = "github.com/lib/pq"
  revision = "v1.2.0"